apiVersion: skaffold/v2alpha/3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ticketing/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: '.'
            src: 'src/**/*.ts'
  
    - image: ticketing/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: '.'
            src: 'src/**/*.ts'
  